confdir = "/etc/confd/apache"

[template]

src = "perInstance.tmpl"

dest = "/zurmo/zurmo/app/protected/config/perInstance.php"

keys = [ "/services/database", "/services/cache" ]

owner = "www-data"
mode = "0775"
