--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    name: apache.zurmo
  name: apache.zurmo
spec: 
  containers: 
    - image: "gtoff/zurmo_apache:kubernetes"
      name: apache
      ports: 
        - containerPort: 80
          hostPort: 80
    - image: icclabcna/zurmo_log_courier_apache
      name: logcourier

