apiVersion: v1
kind: Pod
metadata:
  name: zurmo-webapp-allinone
  labels:
    name: zurmo-webapp-allinone
spec:
  containers:
  - name: apache
    image: gtoff/zurmo_apache:kubernetes
    ports:
    - containerPort: 80
  - name: logcourier
    image: icclabcna/zurmo_log_courier_apache
  - resources:
    limits:
      cpu: 0.5
    image: icclabcna/zurmo_mysql
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      # Change this password!
      value: zurmo
    ports:
    - containerPort: 3306
      name: mysql

