apiVersion: v1
kind: Service
id: zurmo-galera-cluster
metadata:
  labels:
    name: zurmo-galera-cluster
  name: zurmo-galera-cluster
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
    - port: 4444
      targetPort: 4444 
      name: state-snapshot-transfer
    - port: 4567
      targetPort: 4567
      name: replication-traffic 
    - port: 4568
      targetPort: 4568 
      name: incremental-state-transfer 
  selector:
    name: zurmo-galera-cluster 
labels: 
  name: zurmo-galera-cluster
